### ISSUE TITLE
This created a regression where resolvers that do not *return* a `BatchLoader::GraphQL` fail to call `BatchLoader::GraphQL` calls that the resolver uses.

### ISSUE THREAD

**Issue by maletor** [exAspArk/batch-loader#36]
This created a regression where resolvers that do not *return* a `BatchLoader::GraphQL` fail to call `BatchLoader::GraphQL` calls that the resolver uses.

_Originally posted by @maletor in https://github.com/exAspArk/batch-loader/pull/32#issuecomment-464197355_

**Comment by exAspArk** [comment]
Hi @maletor,

Do you use `graphql` gem versions >= 1.8.7? 

* If yes, then upgrading to `batch-loader` version 1.3.0 should have no effect for resolvers which don't return `BatchLoader::GraphQL`. With `graphql` 1.8.7+, batching was already broken because of the breaking changes in the `graphql` gem.
* If you use version `graphql` gem versions < 1.8.7, then resolvers with `BatchLoader::GraphQL` and without should work fine. I.e. it is backward compatible.

Here is the test schema which covers this case:

https://github.com/exAspArk/batch-loader/blob/43e4f62ab5e788e635aeca0a4a01def3f7ee5ca6/spec/fixtures/graphql_schema.rb#L10-L20
