### ISSUE TITLE
usage with sort?

### ISSUE THREAD

**Issue by terencechow** [exAspArk/batch-loader#37]
Given the below, I was under the impression I would be able to avoid the `n+1` request problem. However the below query makes n+1 calls. Am I using this incorrectly? Is there a way to avoid the n+1 problem when trying to sort?

```
User.where(canonical_id: args['ids']).sort{ |a, b|  a.latest_posts.date <=> b.latest_posts.date }

// user model
def latest_posts
    BatchLoader.for(id).batch do |user_ids, loader|
        Posts.where(user_id: user_ids)
        .group('users.id')
        .group_by(&:user_id)
        .each do |user_id, posts|
              // latest_content = ...some function that finds the post with the latest date
              // latest_date = ...some function that finds the post by the latest date
              loader.call(user_id, OpenStruct.new(user_id: user_id, content: latest_content, date: latest_date)
        end
    end
end
```

Edit: After some investigation this appears to be because latest_post is a OpenStruct and sort gets called on a field in the struct. For example `User.where(canonical_id: args['ids']).sort{ |a, b|  a.latest_posts <=> b.latest_posts }` does not result in `n + 1` queries, and also interestingly 
manually invoking the `latest_posts` on each user but NOT fetching a field from the struct also does not do `n + 1` queries:

`User.where(canonical_id: args['ids']).each(&:latest_posts).sort{ |a, b|  a.latest_posts.date <=> b.latest_posts.date }`

Is this something that this gem can fix? Would be nice to be able to sort on a nested field, but it's a bit silly that I have to randomly throw in a `.each(&:latest_posts)` just to prevent the `n+1` queries

**Comment by exAspArk** [comment]
Hi @terencechow,

Thank you for opening the issue! BatchLoader version 0.x had an explicit method to batch and load everything `BatchLoader.sync!(posts)`. But since version 1.x it was removed in favour of automatically batching when objects are used.

I agree that using `.each(&:lazy_something)` might be a bit confusing. Would you prefer having something like:

```rb
users = User.where(canonical_id: args['ids'])
users_with_posts = BatchLoader.preload(users) { |user| user.latest_posts }
users_with_posts.sort { |a, b| ... }
```

E.g. `BatchLoader.preload`, `.load` or something like that could still use `.each(&:lazy_something)` but have a better semantic meaning. One downside is that it's a bit harder to chain the methods. However, people might do something like (more verbose):

```rb
# with Rails
User.where(canonical_id: args['ids'])
  .tap { |users| BatchLoader.preload(users, &:lazy_posts) }
  .sort { |a, b| ... }

# with Ruby 2.5+
User.where(canonical_id: args['ids'])
  .yield_self { |users| BatchLoader.preload(users, &:lazy_posts) } # or .then with Ruby 2.6+
  .sort { |a, b| ... }
```

Do you have any suggestions? :)

**Comment by terencechow** [comment]
I don’t have strong opinions or any suggestion on this really... I’m okay with the preload option though it is more verbose. What about an argument passed to batchloader.load that tells it when it has collected N items then it can load? Might make things less verbose... again I have no strong opinions on this.
