### ISSUE TITLE
Possibility of deadlock

### ISSUE THREAD

**Issue by JanStevens** [exAspArk/batch-loader#55]
Hello,

I was happily refactoring away all my association loading in GraphQL by using a combination of `key` and association reflection. After I changed everything and did a query I get  a `deadlock; recursive locking`, auwsch.

Doing some research it seems that Mutex does not allow reentry while Monitor does. Changing line 101 in batch_loader.rb to `mutex = Monitor.new` does fix the issue locally.

I did some research on it and found this related article: https://japgolly.blogspot.com/2012/04/ruby-mutex-reentrancy.html There is a cost to it but I believe its marginal low (compare to SQL queries). 

So WDYT? Up for MR or am I completely missing the point? 😓

**Comment by JanStevens** [comment]
Ha I found out what I did wrong, I called `loader.call` two times because of a bug in the code

Could this be maybe catched and custom exception raised?

Thanks!

**Comment by exAspArk** [comment]
Hey @JanStevens,

Thank you for tracking down the issue and posting it here! I hope that it'll help other people who experience the same issue.

For now, I'd not "wrap" the thread deadlock error to raise a custom exception. One of the reasons why is because `BatchLoader` allows calling `loader.call` with a custom code block (e.g. for [loading multiple items](https://github.com/exAspArk/batch-loader#loading-multiple-items)). It might potentially confuse people if they see a `BatchLoader` custom exception for their code written in the block, which, for example, raised an unrelated deadlock exception.
